### ISSUE TITLE
No text in the notification

### ISSUE THREAD

**Issue by errakeshpd** [calonso/rails-push-notifications#10]
Insertion 
`=> [#<RailsPushNotifications::Notification:0x007f1a15c33878
  id: 7,
  destinations:
   ["ciJie4Om2aw:APA91bHckWobcMLNzOXxe9eXl0X4FuoDym9IlcBjvWOiwjtq0LptHEdy0ubgUahqb-79TF6X5J9eUUL-TRo3jACQBGmL1vPhP9cSb2TXnVCAU-iIlvQc1Kps-Yg0aUiVhjXZHBAq04Po"],
  app_id: 7,
  app_type: "RailsPushNotifications::GCMApp",
  data: {:text=>"Awesome bags is in Live In near you"},
  results:
   #<RubyPushNotifications::GCM::GCMResponse:0x007f1a15824098
    @canonical_ids=0,
    @failed=0,
    @results=[#<RubyPushNotifications::GCM::GCMResultOK:0x007f1a154037c0>],
    @success=1>,
  success: 1,
  failed: 0,
  sent: true,
  created_at: Thu, 28 Jul 2016 09:50:22 UTC +00:00,
  updated_at: Thu, 28 Jul 2016 09:50:22 UTC +00:00>]`

Notification is receiving but no text is showing in the notification.

PFA.
![screenshot_2016-07-28-15-35-42](https://cloud.githubusercontent.com/assets/5379778/17209131/1aea26a0-54d9-11e6-88f4-211bd5e7d433.png)

**Comment by calonso** [comment]
Hi @errakeshpd 

I think the problem is that you aren't parsing it properly on your device. The sent notification contains the `data` key and it will contain your `{ text: "Awesome ..." }` following the [official documentation](https://developers.google.com/cloud-messaging/http-server-ref#downstream).

I'd suggest printing it in the logs to double check what you're getting and then parse it properly.

Hope it helps.

**Comment by calonso** [comment]
Closing as inactive... Please reopen it if you need further help.
